generate_poem:
  description: >
    Write a poem about {topic}. Ensure the poem is engaging and adheres to the specified sentence count of {sentence_count}.
  expected_output: >
    A heart touching poem on {topic} with sentence count provided by the user {sentence_count}
  agent: poem_generator
